
/**
* HelloWorldServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorld.idl
* sábado 16 de marzo de 2019 07:41:48 PM MST
*/


//*Asignatura: Programacion Integrativa (UACJ)*//
public final class HelloWorldServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public HelloWorldService value = null;

  public HelloWorldServiceHolder ()
  {
  }

  public HelloWorldServiceHolder (HelloWorldService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloWorldServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloWorldServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloWorldServiceHelper.type ();
  }

}
