
/**
* HelloWorldService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorld.idl
* sábado 16 de marzo de 2019 07:41:48 PM MST
*/


//*Asignatura: Programacion Integrativa (UACJ)*//
public interface HelloWorldService extends HelloWorldServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface HelloWorldService
