
/**
* HelloWorldServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorld.idl
* sábado 16 de marzo de 2019 07:41:48 PM MST
*/


//*Asignatura: Programacion Integrativa (UACJ)*//
public interface HelloWorldServiceOperations 
{
  String message (String msg);
} // interface HelloWorldServiceOperations
